#!/usr/bin/env python3
import json
import requests

try:
    req = requests.get('http://rzhunemogu.ru/RandJSON.aspx?CType=11')
    try:
        if req.status_code != 200:
            print("Сегодня без анекдотов :(")
        else:
            json_obj = json.loads(req.text, strict=False)
            print(json_obj['content'])
    except Exception as e:
        print(req.text[12:-2])
except Exception as e:
    print("Сегодня без анекдотов :(")
